description: All static application information required by the FI to create binding offers.
type: object
required:
  - mortgageType
  - propertyInformation
  - requestingParty
properties:
  mortgageType:
    type: string
    description: Type of mortgage request being made.
    example: buy
    enum:
      - buy
      - replacement
      - construction_financing
  propertyInformation:
    $ref: ./PropertyObject.yaml
  requestingParty:
    $ref: ./Party.yaml
  applicationId:
    $ref: ./ApplicationId.yaml
  channelType:
    type: string
    enum:
      - advisor
      - direct
    description: The type of the channel through which the application was submitted.
    example: advisor
  replacedTranches:
    description: Information about the tranche(s) being replaced.
    type: array
    items:
      type: object
      properties:
        replacedTrancheAmount:
          $ref: ./Amount.yaml
          description: The amount of the tranche being replaced.
        replacedTrancheExpiry:
          $ref: ./generic/Date.yaml
          description: The expiration date of the replaced tranche.
          example: '2022-05-03'
        replacedTrancheIssuer:
          type: string
          description: The financial institution that issued the tranche being replaced.
          example: Credit Suisse
  replacementType:
    type: string
    description: Type of replacement. Not required if the mortgage type is "BUY". Possible values are "entire" or "partial".
    example: entire
    enum:
      - entire
      - partial
  tppAdvisorDetail:
    description: Personal information of the TPP advisor.
    type: object
    properties:
      name:
        type: string
        maxLength: 70
        description: The first name of the TPP advisor.
        example: Max
      surName:
        type: string
        maxLength: 70
        description: The last name of the TPP advisor.
        example: Muster
      nameTpp:
        type: string
        maxLength: 70
        description: The name of the TPP firm the advisor belongs to.
        example: Muster Finanz AG
      email:
        type: string
        description: The email address of the TPP advisor.
        example: max.muster@domain.ch
      language:
        type: string
        example: fr
        description: The preferred contact language of the TPP advisor.
        enum:
          - de
          - fr
          - it
          - en
      phone:
        type: string
        description: The phone number of the TPP advisor.
        example: '+41443343456'
      address:
        $ref: ./StructuredAddress.yaml
  tppApplicationId:
    type: string
    description: The application alphanumeric identifier defined by TPP.
    pattern: ^[a-zA-Z0-9]{6,10}$
    example: asd23f
