description: All details regarding a financial institution's (FI) mortgage product, including interest rate type, product names, and variations.
type: object
required:
  - interestRateType
  - names
  - productId
properties:
  interestRateType:
    type: string
    description: The type of interest rate applied to the mortgage product.
    example: libor
    enum:
      - variable
      - libor
      - saron
      - fixed
  names:
    type: array
    description: A list of names for the mortgage product in different languages.
    items:
      type: object
      properties:
        description:
          type: string
          description: A description of the mortgage product name.
          example: Fixed rate mortgage
        language:
          type: string
          description: The language of the product name.
          example: fr
          enum:
            - de
            - fr
            - it
            - en
  productId:
    $ref: ./ProductId.yaml
  productVariations:
    type: array
    description: A list of variations of the mortgage product, detailing the term length, interest rate, and optional SARON period.
    items:
      $ref: ./ProductVariation.yaml
