description: Product variation details.
type: object
properties:
  duration:
    $ref: ./generic/Duration.yaml
  rate:
    $ref: ./generic/InterestRate.yaml
    description: The interest rate.
  saronperiod:
    $ref: ./generic/SaronPeriod.yaml
